### ISSUE TITLE
hover interaction location is still pretty off.. not sure how hard that is to fix... probably not a top priority tho

### ISSUE THREAD

**Issue by erinsinger93** [pkbriggs/project448b#43]

**Comment by jnewcs** [comment]
when you initially enter the bar, that's the spot where the hover box is placed, but as you move the mouse (while still in the bar) the hover stays in the same place. Do we want to keep on moving the bar as you move your mouse through the box?

**Comment by jnewcs** [comment]
fixed in branch 'front_page_changes"
